import type { AnimationDocument } from '../types/document';
import type { SceneElement } from '../types/element';
import type { AnyTrack, NumericTrack, ColorTrack } from '../types/track';
import type { CubicBezierEasing } from '../types/easing';
import { sampleNumber, sampleColor, strokeDashOffset } from './animation';
import { scalarFilterCss, dropShadowCss, composeFilter, SCALAR_FILTERS } from './filters';
import { getPropertyDef } from './properties';
import { cubicBezierCss } from './easingCurve';
import { mergedChannelStops, frameTimes } from './exportSampling';
import { round3 as num } from './format';

/**
 * CSS `@keyframes` serializer (framework-free). Turns the document into clean,
 * pasteable CSS that targets the inlined SVG by `data-anim-id`.
 *
 * Every value is read through the same `sampleNumber`/`sampleColor` the editor
 * preview uses, so the exported animation can't diverge from what's on screen
 * (architecture rule 1). CSS animates `transform` and `filter` as single
 * properties, so the per-property tracks for each are merged into one channel:
 * when those tracks share keyframe times and eases the channel is emitted as a
 * clean per-segment `cubic-bezier()`; otherwise it's baked per frame (DEC-8).
 *
 * The editor pivots rotate/scale about the element's bbox centre via an explicit
 * `translate(o) rotate translate(-o) scale` matrix; the export reproduces it
 * exactly with `transform-box: fill-box; transform-origin: center;` (the two
 * matrices are equal because translations commute).
 */

const TRANSFORM_PROPS: ReadonlySet<string> = new Set([
  'x',
  'y',
  'scale',
  'scaleX',
  'scaleY',
  'rotation',
  'skewX',
  'skewY',
]);
const FILTER_PROPS: ReadonlySet<string> = new Set([
  ...SCALAR_FILTERS,
  'shadowX',
  'shadowY',
  'shadowBlur',
  'shadowColor',
]);

const HEADER = '/* Generated by Kinetic — SVG Motion Studio */';
const EMPTY_MESSAGE = '/* Nothing to export yet — add keyframes to an element. */';

interface Stop {
  readonly time: number;
  /** The CSS value of the channel's property at `time`. */
  readonly value: string;
  /** Outgoing-segment easing; undefined inherits the shorthand's `linear`. */
  readonly easing?: CubicBezierEasing;
}

/** A keyframe time as a percentage of the duration, e.g. `33.333%`. */
function percent(time: number, duration: number): string {
  return `${num((time / duration) * 100)}%`;
}

/** Sanitise a `data-anim-id` into a CSS-ident-safe `@keyframes` name. */
function keyframesName(domRef: string, channel: string): string {
  return `${domRef.replace(/[^a-zA-Z0-9_-]/g, '-')}-${channel}`;
}

/** Find a track by property, ignoring empty (no-keyframe) tracks. */
function numberTrack(tracks: readonly AnyTrack[], property: string): NumericTrack | undefined {
  const track = tracks.find((t) => t.property === property);
  return track !== undefined && track.keyframes.length > 0 ? (track as NumericTrack) : undefined;
}

function colorTrack(tracks: readonly AnyTrack[], property: string): ColorTrack | undefined {
  const track = tracks.find((t) => t.property === property);
  return track !== undefined && track.keyframes.length > 0 ? (track as ColorTrack) : undefined;
}

function anyAnimated(tracks: readonly AnyTrack[]): boolean {
  return tracks.some((track) => track.keyframes.length >= 2);
}

function numericDefault(property: string): number {
  const def = getPropertyDef(property as never);
  return def !== undefined && def.kind === 'number' ? def.defaultValue : 0;
}

/** The `transform` value at `time` from the active transform tracks. */
function transformValue(tracks: readonly AnyTrack[], time: number): string {
  const x = numberTrack(tracks, 'x');
  const y = numberTrack(tracks, 'y');
  const scale = numberTrack(tracks, 'scale');
  const scaleX = numberTrack(tracks, 'scaleX');
  const scaleY = numberTrack(tracks, 'scaleY');
  const rotation = numberTrack(tracks, 'rotation');
  const skewX = numberTrack(tracks, 'skewX');
  const skewY = numberTrack(tracks, 'skewY');
  const parts: string[] = [];
  if (x !== undefined || y !== undefined) {
    parts.push(`translate(${num(sampleNumber(x, time, 0))}px, ${num(sampleNumber(y, time, 0))}px)`);
  }
  if (rotation !== undefined) parts.push(`rotate(${num(sampleNumber(rotation, time, 0))}deg)`);
  if (scale !== undefined || scaleX !== undefined || scaleY !== undefined) {
    const sx = sampleNumber(scale, time, 1) * sampleNumber(scaleX, time, 1);
    const sy = sampleNumber(scale, time, 1) * sampleNumber(scaleY, time, 1);
    parts.push(sx === sy ? `scale(${num(sx)})` : `scale(${num(sx)}, ${num(sy)})`);
  }
  if (skewX !== undefined) parts.push(`skewX(${num(sampleNumber(skewX, time, 0))}deg)`);
  if (skewY !== undefined) parts.push(`skewY(${num(sampleNumber(skewY, time, 0))}deg)`);
  return parts.join(' ');
}

/** The `filter` value at `time` from the active filter tracks. Shared with the GSAP serializer. */
export function filterValue(tracks: readonly AnyTrack[], time: number): string {
  const parts: string[] = [];
  for (const filter of SCALAR_FILTERS) {
    const track = numberTrack(tracks, filter);
    if (track !== undefined) {
      parts.push(scalarFilterCss(filter, sampleNumber(track, time, numericDefault(filter))));
    }
  }
  const shadowX = numberTrack(tracks, 'shadowX');
  const shadowY = numberTrack(tracks, 'shadowY');
  const shadowBlur = numberTrack(tracks, 'shadowBlur');
  const shadowColor = colorTrack(tracks, 'shadowColor');
  if (
    shadowX !== undefined ||
    shadowY !== undefined ||
    shadowBlur !== undefined ||
    shadowColor !== undefined
  ) {
    parts.push(
      dropShadowCss(
        sampleNumber(shadowX, time, numericDefault('shadowX')),
        sampleNumber(shadowY, time, numericDefault('shadowY')),
        sampleNumber(shadowBlur, time, numericDefault('shadowBlur')),
        sampleColor(shadowColor, time, '#000000'),
      ),
    );
  }
  return composeFilter(parts);
}

/** Drop stops whose value equals both neighbours — collapses constant runs in baked output. */
function dropConstantRuns(stops: readonly Stop[]): Stop[] {
  if (stops.length <= 2) return [...stops];
  const kept: Stop[] = [stops[0]!];
  for (let i = 1; i < stops.length - 1; i++) {
    const previous = stops[i - 1]!;
    const current = stops[i]!;
    const next = stops[i + 1]!;
    if (current.value === previous.value && current.value === next.value) continue;
    kept.push(current);
  }
  kept.push(stops[stops.length - 1]!);
  return kept;
}

/**
 * Build the stops for an animated channel. Clean (per-segment cubic-bezier) when
 * the merged members can be expressed with one timing function per segment —
 * including disjoint members such as rotate-then-scale; baked per frame otherwise
 * (DEC-8). `valueAt` samples the merged property value at a time.
 */
function buildStops(
  tracks: readonly AnyTrack[],
  valueAt: (time: number) => string,
  duration: number,
  fps: number,
): Stop[] {
  const plan = mergedChannelStops(tracks, duration);
  if (plan !== null) {
    return plan.map((stop) => ({
      time: stop.time,
      value: valueAt(stop.time),
      easing: stop.easing,
    }));
  }
  const stops = frameTimes(duration, fps).map((time) => ({ time, value: valueAt(time) }));
  return dropConstantRuns(stops);
}

function emitKeyframes(
  name: string,
  property: string,
  stops: readonly Stop[],
  duration: number,
): string {
  const lines = stops.map((stop) => {
    const timing = stop.easing ? ` animation-timing-function: ${cubicBezierCss(stop.easing)};` : '';
    return `  ${percent(stop.time, duration)} { ${property}: ${stop.value};${timing} }`;
  });
  return `@keyframes ${name} {\n${lines.join('\n')}\n}`;
}

function animationEntry(name: string, duration: number): string {
  return `${name} ${num(duration)}s linear infinite`;
}

interface ChannelResult {
  /** Declarations contributed to the element's base rule (static values, dasharray). */
  readonly decls: string[];
  /** A finished `@keyframes` block, when the channel animates. */
  readonly block?: string;
  /** The `animation` shorthand entry, when the channel animates. */
  readonly animation?: string;
}

/** Build one channel: a static base declaration, or a `@keyframes` block + animation. */
function buildChannel(
  domRef: string,
  channel: string,
  property: string,
  members: readonly AnyTrack[],
  valueAt: (time: number) => string,
  duration: number,
  fps: number,
): ChannelResult {
  if (!anyAnimated(members)) {
    return { decls: [`${property}: ${valueAt(0)}`] };
  }
  const name = keyframesName(domRef, channel);
  const stops = buildStops(members, valueAt, duration, fps);
  return {
    decls: [],
    block: emitKeyframes(name, property, stops, duration),
    animation: animationEntry(name, duration),
  };
}

/** CSS for one element: its base rule plus any `@keyframes` blocks, or null when it has no animation. */
function exportElement(
  element: SceneElement,
  tracks: readonly AnyTrack[],
  duration: number,
  fps: number,
): { rule: string; blocks: string[] } | null {
  const decls: string[] = [];
  const blocks: string[] = [];
  const animations: string[] = [];

  const collect = (result: ChannelResult): void => {
    decls.push(...result.decls);
    if (result.block !== undefined) blocks.push(result.block);
    if (result.animation !== undefined) animations.push(result.animation);
  };

  const transformMembers = tracks.filter(
    (t) => TRANSFORM_PROPS.has(t.property) && t.keyframes.length > 0,
  );
  const usesTransform = transformMembers.length > 0;
  if (usesTransform) {
    collect(
      buildChannel(
        element.domRef,
        'transform',
        'transform',
        transformMembers,
        (t) => transformValue(transformMembers, t),
        duration,
        fps,
      ),
    );
  }

  const opacity = numberTrack(tracks, 'opacity');
  if (opacity !== undefined) {
    collect(
      buildChannel(
        element.domRef,
        'opacity',
        'opacity',
        [opacity],
        (t) => num(sampleNumber(opacity, t, 1)),
        duration,
        fps,
      ),
    );
  }

  const fill = colorTrack(tracks, 'fill');
  if (fill !== undefined) {
    collect(
      buildChannel(
        element.domRef,
        'fill',
        'fill',
        [fill],
        (t) => sampleColor(fill, t, '#000000'),
        duration,
        fps,
      ),
    );
  }

  const stroke = colorTrack(tracks, 'stroke');
  if (stroke !== undefined) {
    collect(
      buildChannel(
        element.domRef,
        'stroke',
        'stroke',
        [stroke],
        (t) => sampleColor(stroke, t, '#000000'),
        duration,
        fps,
      ),
    );
  }

  const strokeWidth = numberTrack(tracks, 'strokeWidth');
  if (strokeWidth !== undefined) {
    collect(
      buildChannel(
        element.domRef,
        'strokeWidth',
        'stroke-width',
        [strokeWidth],
        (t) => num(sampleNumber(strokeWidth, t, 1)),
        duration,
        fps,
      ),
    );
  }

  const draw = numberTrack(tracks, 'draw');
  if (draw !== undefined) {
    const length = element.pathLength || 0;
    decls.push(`stroke-dasharray: ${num(length)}px`);
    collect(
      buildChannel(
        element.domRef,
        'draw',
        'stroke-dashoffset',
        [draw],
        (t) => `${num(strokeDashOffset(length, sampleNumber(draw, t, 100)))}px`,
        duration,
        fps,
      ),
    );
  }

  const filterMembers = tracks.filter(
    (t) => FILTER_PROPS.has(t.property) && t.keyframes.length > 0,
  );
  if (filterMembers.length > 0) {
    collect(
      buildChannel(
        element.domRef,
        'filter',
        'filter',
        filterMembers,
        (t) => filterValue(filterMembers, t),
        duration,
        fps,
      ),
    );
  }

  if (decls.length === 0 && animations.length === 0) return null;

  const head = usesTransform ? ['transform-box: fill-box', 'transform-origin: center'] : [];
  const allDecls = [...head, ...decls];
  if (animations.length > 0) allDecls.push(`animation: ${animations.join(', ')}`);
  const body = allDecls.map((decl) => `  ${decl};`).join('\n');
  const rule = `[data-anim-id="${element.domRef}"] {\n${body}\n}`;
  return { rule, blocks };
}

/** Serialize the whole document to CSS `@keyframes` + per-element rules. */
export function exportCss(doc: AnimationDocument): string {
  const sections: string[] = [];
  for (const element of doc.elements) {
    const tracks = doc.tracks.filter((track) => track.elementId === element.id);
    if (tracks.length === 0) continue;
    const result = exportElement(element, tracks, doc.duration, doc.fps);
    if (result === null) continue;
    sections.push(result.rule, ...result.blocks);
  }
  if (sections.length === 0) return EMPTY_MESSAGE;
  return [HEADER, ...sections].join('\n\n') + '\n';
}
